### ISSUE TITLE
SELL/BUY loop

### ISSUE THREAD

**Issue by d4r1as** [andresilvasantos/bitprophet#13]
This needs a fix :)

![photo_2018-04-30_22-39-45](https://user-images.githubusercontent.com/2236155/39449108-736cc872-4cc7-11e8-8cc0-dc930120b83c.jpg)

**Comment by andresilvasantos** [comment]
Yes, will be fixed in the next commit. :thumbsup:

**Comment by itsjNathan** [comment]
im on the latest version of Bitprophet v0.6.7  and this bug is not already solved

![image](https://user-images.githubusercontent.com/31687526/39612146-7d431e94-4f8f-11e8-83ee-37f7b3cc6276.png)

**Comment by andresilvasantos** [comment]
Are you using buydip.js? If yes, exactly from the 0.6.7?

**Comment by itsjNathan** [comment]
yes, buydip from the version 0.6.7
i already tried to uninstall the BitProphet then install it again but the bug is still there.

**Comment by itsjNathan** [comment]
by the way this is my configuration in index.js

module.exports = {
    strategies: {
        alertsrsi: {
            name: "Alerts RSI",
            targetMarket: "BTC"
        },
        alertsichimoku: {
            name: "Alerts Ichimoku",
            targetMarket: "BTC"
        },
        buydip: {
            name: "Buy Dip",
            paperTrading: false,
            buyAmountMarket: 0.002,
            profitTarget: 10.0,
            maxLoss: 0.8,
            maxTradingPairs: 10,
            targetMarket: "BTC"
        }
    }
}

**Comment by andresilvasantos** [comment]
Did you install from NPM? Do you have a custom strategiesDir option?

**Comment by andresilvasantos** [comment]
The problem, that I believe was solved, was in the strategy buydip.js itself. If you have a strategiesDir directory and copied there buydip.js before 0.6.5, even if you update to the latest version, the bug will still happen, because it will be present in your copied version of the buydip.js.

**Comment by itsjNathan** [comment]
i dont have any custom strategies. i only use the default buydip.js 

this is the code of my index.js i didnt set any strategiesDir

const bitprophet = require('bitprophet')
bitprophet.options({
    binance: {
        key: "XXXXXX",
        secret: "XXXXXXX*"
    },
    telegram: {
        chatId: "XXXXXX",
        token: "XXXXXX"
    },
    discord: {
        chatId: "YOUR_DISCORD_CHANNEL_ID",
        token: "YOUR_DISCORD_BOT_TOKEN"
    }
})
 
bitprophet.start()

**Comment by andresilvasantos** [comment]
Strange, it was happening for me and after the fix it never happened again. I'll take a look this.
In the meantime, you can fix it by copying the strategies into a custom dir, adding the strategiesDir option and commenting the problematic part from buydip.js like this:

```
       /*var sellDiff = pair.amountToSell - order.amount * (1 - order.partFill)

        //Sell order price or amount mismatch
        if(order.price.toFixed(8) != pair.sellTarget.toFixed(8) || sellDiff >= parseFloat(bp.vars.pairsInfo[pair.name].filters.stepSize)) {
            if(pair.trySellTimestamp && Date.now() - pair.trySellTimestamp < 5 * 1000) return
            pair.trySellTimestamp = Date.now()
            recreateSellOrder()
        }
        else {*/
            var chart5m = pair.functions.chart(intervalsWatch[1]).ticks
            var lastClose = parseFloat(chart5m[chart5m.length - 1].close)

            var activateStopLoss = strategy.manageStopLoss(pair, lastClose)
            if(activateStopLoss) recreateSellOrder()
        //}
```

The commented part is just a safe procedure in case the price or the amount of the sell order mismatchs what it should be.

**Comment by itsjNathan** [comment]
okay thanks i will try it
