### ISSUE TITLE
tracking multiple/all pair on binance

### ISSUE THREAD

**Issue by onthetunnel** [andresilvasantos/bitprophet#27]
Hello , can this project auto tracking all BTC pair on binance and auto order the coin is on uptrend(like DCA) and auto  sell these coin has hit the profit % or auto sell it for stop loss ? , Thanks You !

**Comment by andresilvasantos** [comment]
Yes, completely possible, but you'll have to write the strategy. I can help you if you get stuck.

What is DCA?

**Comment by onthetunnel** [comment]
Thanks for you reply ! i dont know how to setting for doing one strategy tracking all pair and auto order auto sell, can you help me please ...and the DCA is dollar cost average. ..hope you can help me .. and this project is awesome ! Thanks You!

**Comment by andresilvasantos** [comment]
I'm short on time, but if you add me on Telegram @andre_silvasantos I can give you some hints. :wink:
