### ISSUE TITLE
Missing trading pairs reported in list command

### ISSUE THREAD

**Issue by mwelsford** [andresilvasantos/bitprophet#28]
version: v0.6.18

Not all the valid trading pairs for a given market are reported using the list <strategy> command.  I'm running the alertsrsi strategy with the following configuration in the index.js file.

```
alertsrsi: {
       name: "Alerts RSI",
       maxTradingPairs: 5,
       excludeTokens: ["TRX", "ETH", "ADA", "BCC", "LTC", "ONT", "ICX", "ETC", "TUSD", "QTUM", "XLM"],
       targetMarket: "USDT"
}
```

and get the bot reports the following 4 tokens as valid:

_Valid Pairs [4]:
#BNB/USDT
#BTC/USDT
#NEO/USDT
#XRP/USDT_ 

I expect at IOTA, EOS to be listed as well.

**Comment by andresilvasantos** [comment]
Check the `alertsrsi.js` file.
Inside `checkValidWorkingPair` function, it is excluding pairs in the following line:

`setPairValid(volume24h >= 100 && stoch5mAvg >= 25 && maxDiff5m < 60)`

If the pair doesn't match the above condition, it won't be a valid pair:

* Volume needs to be higher than 100 for the past 24h (in this case USDT);
* Stochastics average for the last 2 hours need to be higher than 25;
* Max diff between the highest price and the lowest price needs to be below 60% (this one will avoid pump & dumps).

Try to adjust that condition or remove everything and see if all tokens appear, like this:

`setPairValid(true);`

**Comment by mwelsford** [comment]
Thanks for the suggestion.

I've tried adjusting the condition to true and no change.  To ensure it's reaching that point in the code I set `setPairValid(false)` and no pairs were displayed as expected.

Is there any way that I can confirm that those pairs are being passed to the `checkValidWorkingPair` function?

Adding `console.log(pair)` to the `checkValidWorkingPair` yields the following debug output, e.g. is for IOTA.  The function is invoked for the start command only and not the list command.

`{ name: 'IOTAUSDT',
  token: 'IOTA',
  market: 'USDT',
  chatName: '#IOTA/USDT',
  functions: 
   create {
     name: [Function],
     tokenName: [Function],
     marketName: [Function],
     chatName: [Function],
     lastPrice: [Function],
     chart: [Function],
     initChartInterval: [Function],
     chartsNeedUpdate: [Function],
     singleChartUpdate: [Function],
     startChartUpdates: [Function],
     stopChartUpdates: [Function],
     addWatcherChartUpdates: [Function],
     removeWatcherChartUpdates: [Function],
     chartUpdatesActive: [Function],
     ensureChartUpdates: [Function],
     profit: [Function],
     addProfit: [Function],
     accountProfit: [Function],
     addAccountProfit: [Function],
     resetProfits: [Function] },
  processing: false,
  status: -1,
  entryPrice: 0,
  sellTarget: 0,
  amountToSell: 0,
  stopLoss: { stopPrice: 0, sellPrice: 0 },
  orders: [],
  forceSell: false,
  lastValidCheck: -1,
  profit: 0,
  accountProfit: 0,
  alertSent: false }`

**Comment by andresilvasantos** [comment]
Ok, I know what's going on.

```
if(chart1h.length < 500 || chart5m.length < 500) {
	setPairValid(false)
	return
}
```

This ensures there are enough candlesticks to work with to avoid new tokens or empty return results from Binance. Both EOS/USDT and IOTA/USDT are relatively new (less than 20 days). The first condition is to have at least 500 candlesticks for 1h timeframe (which sums up to almost 21 days). So, you can lower that value and they will pass through.

Anyway, you can always `console.log(pair.name)` at the beginning of checkValidWorkingPairs and check the console to see if those pairs appear.

**Comment by mwelsford** [comment]
Found why they are getting rejected.  Neither EOS or IOTA are passing the charts length checks in the `checkValidWorkingPair` function.

Pair name:  EOSUSDT
chart1h.length:  479
chart5m.length:  500

Pair name:  IOTAUSDT
chart1h.length:  403
chart5m.length:  500

Is it OK to change the check from 500 to a lower number?   Why was 500 chosen?

**Comment by mwelsford** [comment]
Thanks for the explanation.  All making sense now.

**Comment by andresilvasantos** [comment]
Nice! Closing the issue.
