### ISSUE TITLE
Selling for 0.27 or 0.07% profits

### ISSUE THREAD

**Issue by softwareklinic** [andresilvasantos/bitprophet#3]
I have setting for 5% profit exit in the index.js --- but it keeps existing at 0.27% or 0.07% profits... does it identify that the coin might be in downward trend and existing the positions... if yes -- why would it pick the coin in 1st place... just trying to learn... not putting a lot of money... only which can help me learn and i dont mind losing in the process.

**Comment by softwareklinic** [comment]
E.g XLM it bought for 0.00004351 ---> put a sell at 0.00004569 ---> sold actually at 0.00004360

**Comment by andresilvasantos** [comment]
Buy Dip has implemented stop loss and trailing profits with the following code:

```
var activateStopLoss = strategy.manageStopLoss(pair, lastClose)
if(activateStopLoss) recreateSellOrder()
```

By default, the limit order is triggered when the price falls 0.60%.
It is auto adjusting the stop loss so if the price starts to rise to let's say 1.7% from the buying price, and then it falls, you collect at least 1.1% of profits.

And probably that's what's happening.

What you can do:

**1** - Remove the trailing profits, but keep the stop loss, so if the price rises to 0.6% the stop loss will be adjusted to 0% and this way you won't have any losses, but it won't be adjusted any further:

```
var activateStopLoss = strategy.manageStopLoss(pair, lastClose, 1)
if(activateStopLoss) recreateSellOrder()
```

**2** - Adjust the trailing percentage to a bigger value (1.2% as an example):

```
var activateStopLoss = strategy.manageStopLoss(pair, lastClose, 2, 0.012)
if(activateStopLoss) recreateSellOrder()
```

**3 (not recommended)** - Remove that part of the code, so there's no stop loss at all.

**Comment by softwareklinic** [comment]
Made the change - testing

**Comment by softwareklinic** [comment]
going with #2

**Comment by andresilvasantos** [comment]
If you changed the condition in #2 how can it give you the same error?

Edit: Oh, the second option, not the second issue. Got it!

**Comment by andresilvasantos** [comment]
Closing this issue, feel free to reopen it if needed.
