### ISSUE TITLE
buyAmountMarket Question

### ISSUE THREAD

**Issue by mwelsford** [andresilvasantos/bitprophet#31]
Hi,

In the index.js for the strategies, is the `buyAmountMarket` in the targetMarket currency?  For example with `targetMarket: "USDT"` then is the `buyAmountMarket: 200` in USD?

Thanks

Awesome effort btw!

**Comment by andresilvasantos** [comment]
Yes, that's it. As my strategies are only for the BTC market, I didn't test BitProphet with other markets, but I know people that do.

To avoid having losses, I advise to use any strategy first with paper trading active. Let me know if you run into problems.

>Awesome effort btw!

Thank you! :blush:
