### ISSUE TITLE
Run buydip against ETH pairs

### ISSUE THREAD

**Issue by bitcoiniodev** [andresilvasantos/bitprophet#35]
Hello Andre

What should I do to run buydip with Ethereum pairs? 

Thanks!

**Comment by andresilvasantos** [comment]
Change your strategies configuration file to something like this:

```
module.exports = {
	strategies: {
		buydip: {
			name: "Buy Dip",
			paperTrading: true,
			buyAmountMarket: 0.2,
			profitTarget: 2.4,
			maxLoss: 0.8,
			maxTradingPairs: 5,
			targetMarket: "ETH"
		}
	}
}
```

**Comment by bitcoiniodev** [comment]
Is the 100BTC volume  auto recalculated or some fix needed?

**Comment by andresilvasantos** [comment]
It will be 100ETH volume for the last 24 hours, so if you want different than that, you'll need to fix it.

**Comment by bitcoiniodev** [comment]
Thanks!
