### ISSUE TITLE
Indicators

### ISSUE THREAD

**Issue by bitcoiniodev** [andresilvasantos/bitprophet#38]
Do you code your own indicators cause you do not like these -
https://github.com/anandanand84/technicalindicators
or there is some other reason

**Comment by andresilvasantos** [comment]
Nice, I didn't know that project.

I think I've searched at the time for indicators libraries, but I found coding them the best decision to make (this was not meant to be an open source project from the start, so my only focus was to automate my strategies as quick as possible and to make money out of it).

* BitProphet's indicators accept and work with the data Binance returns;
* There's no playing around when dealing with money, making them from scratch and double check every indicator would be a strong security factor for me;
* I couldn't find a library that had indicators I wanted from the start (Ichimoku and Support Bases, for example).

Thank you for letting me know though.
