### ISSUE TITLE
ETIMEDOUT WebSocket Error

### ISSUE THREAD

**Issue by Fluffologist** [andresilvasantos/bitprophet#40]
I am getting an error due to time out issues. How should I go about fixing this?

I have all the dependencies installed via npm as well.

After I initialize a strategy through telegram the errors begin to pop up a few seconds later.

Here is a log of the info in the console.

Initialization complete.
Waiting connection for user data updates: 01:42:05
Waiting connection for user data updates: 01:42:06
Waiting connection for user data updates: 01:42:08
Waiting connection for user data updates: 01:42:09
Waiting connection for user data updates: 01:42:11
Waiting connection for user data updates: 01:42:12
Waiting connection for user data updates: 01:42:14
Loading connection for user data updates: 01:42:15
Waiting connection for user data updates: 01:42:17
Waiting connection for user data updates: 01:42:18
Waiting connection for user data updates: 01:42:20
Waiting connection for user data updates: 01:42:21
Waiting connection for user data updates: 01:42:23
Waiting connection for user data updates: 01:42:24
[ 'WebSocket error: btcusdt@kline_5m (ETIMEDOUT) connect ETIMEDOUT 54.92.26.88:9443' ]
[ 'WebSocket closed: btcusdt@kline_5m (1006)' ]
[ 'WebSocket error: btcusdt@kline_15m (ETIMEDOUT) connect ETIMEDOUT 54.92.26.88:9443' ]
[ 'WebSocket closed: btcusdt@kline_15m (1006)' ]
Loading connection for user data updates: 01:42:26
[ 'WebSocket error: Yc31tSDcII2ptOsr4pk46EW2a9UGK74opWybIuJ7nyi9fcd7JnCcF9apXDkf (ETIMEDOUT) connect ETIMEDOUT 54.92.26.88:9443' ]
[ 'WebSocket closed: Yc31tSDcII2ptOsr4pk46EW2a9UGK74opWybIuJ7nyi9fcd7JnCcF9apXDkf (1006)' ]
[ 'WebSocket error: btcusdt@kline_5m (ETIMEDOUT) connect ETIMEDOUT 54.92.26.88:9443' ]
[ 'WebSocket closed: btcusdt@kline_5m (1006)' ]
[ 'WebSocket error: btcusdt@kline_15m (ETIMEDOUT) connect ETIMEDOUT 54.92.26.88:9443' ]
[ 'WebSocket closed: btcusdt@kline_15m (1006)' ]
Waiting connection for user data updates: 01:42:27
[ 'WebSocket error: btcusdt@kline_5m (ETIMEDOUT) connect ETIMEDOUT 54.92.26.88:9443' ]
[ 'WebSocket closed: btcusdt@kline_5m (1006)' ]
[ 'WebSocket error: btcusdt@kline_15m (ETIMEDOUT) connect ETIMEDOUT 54.92.26.88:9443' ]
[ 'WebSocket closed: btcusdt@kline_15m (1006)' ]

**Comment by andresilvasantos** [comment]
@Fluffologist this was probably a Binance problem. I've had this problem even when their site was working, but the API was down. Did you manage to make BitProphet work?

**Comment by stumyers02** [comment]
I'm in a very similar situation. I have no problem running the script through the Run kit playground (and receive telegram messages) but have been unable to successfully get it running on my computer. I installed node.js and followed instructions. When I run the script on my computer, I get the following... but I never get any messages on Telegram. Am I forgetting a step? I'm a node newbie and appreciate any help!

Initialization complete.
Waiting connection for user data updates: 01:42:05
Waiting connection for user data updates: 01:42:06
Waiting connection for user data updates: 01:42:08
Waiting connection for user data updates: 01:42:09
Waiting connection for user data updates: 01:42:11
Waiting connection for user data updates: 01:42:12
Waiting connection for user data updates: 01:42:14

**Comment by stumyers02** [comment]
Nevermind, got it!
