### ISSUE TITLE
i cant install bitporphet

### ISSUE THREAD

**Issue by 9121511** [andresilvasantos/bitprophet#42]
i run on "home" on linux
npm install bitprophet --save

results on this mesage:
user@user1:~$ npm install bitprophet --save
npm WARN checkPermissions Missing write access to /home/user/node_modules/bitprophet
npm WARN enoent ENOENT: no such file or directory, open '/home/user/package.json'
npm WARN discord.js@11.3.2 requires a peer of bufferutil@^3.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN user No description
npm WARN user No repository field.
npm WARN user No README data
npm WARN user No license field.

npm ERR! path /home/user/node_modules/bitprophet
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/home/user/node_modules/bitprophet'
npm ERR!  { Error: EACCES: permission denied, access '/home/user/node_modules/bitprophet'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/home/user/node_modules/bitprophet\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/user/node_modules/bitprophet' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-07-12T03_51_08_237Z-debug.log

**Comment by andresilvasantos** [comment]
You need to initialize the package.json file first. Please follow [this tutorial](http://weaintplastic.github.io/web-development-field-guide/Development/Frontend_Development/Setting_up_your_project/Setup_Dependency_Managers/Node_Package_Manager/Initialize_NPM_on_a_new_project.html).
And it is better if you create a folder just for this, for example: `/home/user/test`, otherwise it is difficult to analyse problems if the working directory is full of other files.

**Comment by 9121511** [comment]
i run > npm init on test folder....later
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', 'bitprophet' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose npm-session b08d3146d16aa15e
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/bitprophet 523ms (from cache)
8 silly pacote tag manifest for bitprophet@latest fetched in 542ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly saveTree bitprophet@1.0.0
14 verbose stack Error: Refusing to install package with name "bitprophet" under a package
14 verbose stack also called "bitprophet". Did you name your project the same
14 verbose stack as the dependency you're installing?
14 verbose stack
14 verbose stack For more information, see:
14 verbose stack     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
14 verbose stack     at checkSelf (/usr/lib/node_modules/npm/lib/install/validate-args.js:64:14)
14 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
14 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
14 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
14 verbose stack     at hasMinimumFields (/usr/lib/node_modules/npm/lib/install/validate-args.js:30:12)
14 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
14 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
14 verbose stack     at chain (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
14 verbose stack     at /usr/lib/node_modules/npm/lib/install/validate-args.js:16:5
14 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
14 verbose stack     at Array.forEach (<anonymous>)
14 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
14 verbose stack     at Array.forEach (<anonymous>)
14 verbose stack     at asyncMap (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
14 verbose stack     at module.exports (/usr/lib/node_modules/npm/lib/install/validate-args.js:15:3)
14 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
15 verbose cwd /home/user/test/2
16 verbose Linux 4.13.0-46-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "bitprophet"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ENOSELF

**Comment by 9121511** [comment]
i run this:
user@user1:~/test/2$ npm init bitprophet
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (2) bitprophet
version: (1.0.0) 
description: dasd
entry point: (index.js) 
test command: help
git repository: https://www.npmjs.com/package/bitprophet
keywords: bot
author: fds
license: (ISC) 
About to write to /home/user/test/2/package.json:

{
  "name": "bitprophet",
  "version": "1.0.0",
  "description": "dasd",
  "main": "index.js",
  "scripts": {
    "test": "help"
  },
  "repository": {
    "type": "git",
    "url": "https://www.npmjs.com/package/bitprophet"
  },
  "keywords": [
    "bot"
  ],
  "author": "fds",
  "license": "ISC"
}


Is this ok? (yes) 
user@user1:~/test/2$

**Comment by andresilvasantos** [comment]
@9121511 did you manage to make it work?

**Comment by aycanurun** [comment]
root@110:/var/opt/bitprophet-master# npm install bitprophet --save
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "bitprophet" under a package
npm ERR! also called "bitprophet". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-15T19_30_24_447Z-debug.log
