### ISSUE TITLE
Flood messages when alert

### ISSUE THREAD

**Issue by hiddenlucas** [andresilvasantos/bitprophet#46]
Hello,
How to avoid flood messages when alert? I create alert when EMA15 cross EMA50 and  when it's happen I get flood.  It's possible is change pair.functions.chart from ticks to last created/closed candle?

`process: function(strategy, pair) {
		if(!pair.functions.chartUpdatesActive(intervalsWatch)) {
			pair.functions.ensureChartUpdates(intervalsWatch)
			return
		}

		var chart4h = pair.functions.chart(intervalsWatch[0]).ticks
		var chart1h = pair.functions.chart(intervalsWatch[1]).ticks

		if(chart4h.length < 500 || chart1h.length < 500) return

		
		var ema4h15 = bp.indicators.ema(chart4h, 15, 100, 2)
		var ema4h50 = bp.indicators.ema(chart4h, 50, 100, 2)
		
		var ema1h15 = bp.indicators.ema(chart1h, 15, 100, 2)
		var ema1h50 = bp.indicators.ema(chart1h, 50, 100, 2)
		
		var ema4h15last = ema4h15[0]
		var ema4h50last = ema4h50[0]
		var ema4h15curr = ema4h15[1]
		var ema4h50curr = ema4h50[1]
		
		var ema1h15last = ema1h15[0]
		var ema1h50last = ema1h50[0]
		var ema1h15curr = ema1h15[1]
		var ema1h50curr = ema1h50[1]
		
		if( ema4h15last < ema4h50last && ema4h15curr >= ema4h50curr ){
			console.log(pair.name, " @ EMA15 at 4h cross EMA50 ❗️")
		}
		
		
		if(!pair.alertSent && ema4h15last < ema4h50last && ema4h15curr >= ema4h50curr) {
			strategy.sendMessage(pair, " @ EMA15 at 4h cross EMA50 ❗️")
			pair.alertSent = true
		}
		else if(ema4h15curr > ema4h50curr ||  ema4h15last < ema4h50last ) {
			pair.alertSent = false
		}
		
		if(!pair.alertSent && ema1h15last < ema1h50last && ema1h15curr >= ema1h50curr) {
			strategy.sendMessage(pair, " @ EMA15 at 1h cross EMA50 ❗️")
			pair.alertSent = true
		}
		else if(ema1h15curr > ema1h50curr ||  ema1h15last < ema1h50last) {
			pair.alertSent = false
		}	`

![telegram flood](https://i.imgur.com/IusjUAN.png)

**Comment by andresilvasantos** [comment]
Hi @hiddenlucas !

I don't think your ELSE-IF logic is ok, for example for the 4H cross:

```
if(!pair.alertSent && ema4h15last < ema4h50last && ema4h15curr >= ema4h50curr) {
	strategy.sendMessage(pair, " @ EMA15 at 4h cross EMA50 ❗️")
	pair.alertSent = true
}
else if(ema4h15curr > ema4h50curr ||  ema4h15last < ema4h50last ) { // This is wrong
	pair.alertSent = false
}
```

The else-if should have something like this

```
else if(ema4h15last >= ema4h50last || ema4h15curr < ema4h50curr) {
	pair.alertSent = false
}
```

Let me know if this fixes your spam messages.
