### ISSUE TITLE
rename commands

### ISSUE THREAD

**Issue by ramyarrk** [andresilvasantos/bitprophet#49]
hi
I want to know how to rename command?
for example rename list command to text?

**Comment by asif-shaikh** [comment]
It's simple and easy though.
Open `commands\index.js` file, and add/rename command list.

For example, if you want _ls_ instead of _list_ or want both, you can change it something like this.

```javascript
list: {
        triggers: ["list", "ls"],
        description: "Lists all strategies. Specifying a strategy id, will list all valid / trading pairs for the given strategy"
        },
```

>_Do not rename files if you are a non-techie._

**Comment by ramyarrk** [comment]
tnx 
I want to make keyboard for this telegram bot.
can you tell me how to do it?
