### ISSUE TITLE
I can run

### ISSUE THREAD

**Issue by MaximMyDev** [andresilvasantos/bitprophet#53]
Hi, sorry for the simple question, I am a beginner programmer and just learning. I just downloaded the current version of your program. When I try to run it
npm install bitprophet --save
I get an error
\bitprophet>npm install bitprophet --save
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "bitprophet" under a package
npm ERR! also called "bitprophet". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Root\AppData\Roaming\npm-cache\_logs\2021-03-02T05_47_49_884Z-debug.log==
I also tried to initialize this
npm init (bitprophet)
what should I do?

**Comment by aycanurun** [comment]
Find package.json file and open it. Change the project name ("name": "bitprophet",) (eg: ” "name": "bitprophet111",) and save file. then try again install “npm install bitprophet —save”
