### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by d4r1as** [andresilvasantos/bitprophet#7]
Hi @andresilvasantos 

Just wanted to start with "this is not an issue" 😄 

I would like to contribute more to this project and I was wondering if you have already a development plan .. and or if  you are using a project management tool to organize yourself. 

All the best
I

**Comment by andresilvasantos** [comment]
Hey, that's awesome!

What management tools do you know? Not using any at the moment and I'm all open to suggestions.

Add this group in telegram if you want to discuss this in realtime: https://t.me/bitprophethub
