### ISSUE TITLE
Add MACD indicator

### ISSUE THREAD

**Issue by andresilvasantos** [andresilvasantos/bitprophet#9]
This important indicator is still missing and it's a great addition to the project:
http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:moving_average_convergence_divergence_macd

**Comment by supershwa** [comment]
Submitted a pull request with MACD and ZigZag - please test these.  ZigZag should be OK, but I need a second set of eyes to check MACD.  Would be nice to have a UI to visibly verify the numbers on a chart!  :)

**Comment by nilamoromete** [comment]
Also indicators like ATR, ADX+DI will be nice

**Comment by andresilvasantos** [comment]
@nilamoromete We'll be working on it!
